In [1]:
import numpy as np
import torch
torch.cuda.is_available()

True

## Tensor Basics

In [2]:
## numpy array to tensor

arr = np.array([[1,3,5,7,9,0],[1,2,3,4,5,6]])
print(arr, '\n')
tensor = torch.from_numpy(arr)
print(type(tensor))
tensor

[[1 3 5 7 9 0]
 [1 2 3 4 5 6]] 

<class 'torch.Tensor'>


tensor([[1, 3, 5, 7, 9, 0],
        [1, 2, 3, 4, 5, 6]])

In [3]:
## Indexing

print(tensor[0])
print(tensor[1])
print(tensor[0, 3])
print(tensor[1, :3])
print(tensor[0, :-1])

tensor([1, 3, 5, 7, 9, 0])
tensor([1, 2, 3, 4, 5, 6])
tensor(7)
tensor([1, 2, 3])
tensor([1, 3, 5, 7, 9])


In [4]:
tensor_cpy = tensor
print(tensor_cpy)
print(id(tensor))
print(id(tensor_cpy))

tensor([[1, 3, 5, 7, 9, 0],
        [1, 2, 3, 4, 5, 6]])
139782801644832
139782801644832


In [5]:
## Cloning/copying a tensor
tensor_cloned = tensor.clone()
print("Original tensor id: {}".format(id(tensor)))
print("Cloned tensor id : {}\n".format(id(tensor_cloned)))

tensor_cpy = torch.tensor(arr)
print("Original tensor id: {}".format(id(tensor)))
print("Copied tensor id : {}\n".format(id(tensor_cpy)))

Original tensor id: 139782801644832
Cloned tensor id : 139782676507376

Original tensor id: 139782801644832
Copied tensor id : 139782676507456



In [6]:
## Manipulating values
tensor_cpy[1,3] = -999  # Changing values in copy of tensor 
print("Original tensor: \n{}".format(tensor))
print("Copied tensor: \n{}\n".format(tensor_cpy))

Original tensor: 
tensor([[1, 3, 5, 7, 9, 0],
        [1, 2, 3, 4, 5, 6]])
Copied tensor: 
tensor([[   1,    3,    5,    7,    9,    0],
        [   1,    2,    3, -999,    5,    6]])



In [7]:
## Creating tensors
tensor = torch.zeros(4,2, dtype = torch.float32)
tensor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
## Arithmetic operations
a = torch.tensor([3,4,5,6,7])
b = torch.tensor(np.arange(0,20,4))
c = torch.zeros(a.shape[0])
print(a,'\n', b)

tensor([3, 4, 5, 6, 7]) 
 tensor([ 0,  4,  8, 12, 16])


In [10]:
# ADD
torch.add(a,b, out = c)
print(c)

# <tensor>.sum()
print(f"sum = {c.sum()}") 

tensor([ 3.,  8., 13., 18., 23.])
sum = 65.0


In [11]:
## Dot Product and multiply operation
print(f"Dot Product : {a.dot(b)}")
print(f"Simple multiply operation: {a.mul(b)}")

Dot Product : 240
Simple multiply operation: tensor([  0,  16,  40,  72, 112])


In [12]:
## MATRIX MULTLIPLICATION
a = torch.tensor(np.arange(10).reshape(2,-1))
b = torch.tensor(np.arange(10).reshape(5,-1))
print(a, '\n')
print(b, '\n')
print("matrix multiplication:")
a.matmul(b)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) 

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]) 

matrix multiplication:


tensor([[ 60,  70],
        [160, 195]])

In [13]:
# Another way of matrix multiply
torch.mm(a,b)

tensor([[ 60,  70],
        [160, 195]])